# Generated by Django 5.0 on 2024-10-09 07:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vendor_date_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default='Vendor.jpg', upload_to=core.models.user_directory_path),
        ),
    ]
