# Generated by Django 5.0 on 2024-10-13 09:31

import core.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_productimages_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='Product.jpg', upload_to=core.models.user_directory_path, validators=[core.validators.validate_image_size]),
        ),
    ]
