# Generated by Django 5.0 on 2024-10-13 10:37

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to='product-images', validators=[core.validators.validate_image_size]),
        ),
    ]
