# Generated by Django 5.0 on 2024-10-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_productimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='product_type', max_length=100),
        ),
    ]
