# Generated by Django 5.0 on 2024-10-18 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_productimages_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='date',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='product_status',
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.99, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.99, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.99, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.product'),
        ),
    ]
