# Generated by Django 5.0 on 2024-10-23 17:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_productreview_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='image',
            field=models.ImageField(default='user.jpg', upload_to=core.models.user_directory_path),
        ),
    ]
