# Generated by Django 5.0 on 2024-10-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_productreview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='image',
        ),
    ]
