# Generated by Django 5.0 on 2024-10-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_filterpreference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilterPreference',
        ),
    ]
