# Generated by Django 5.0 on 2024-11-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_address_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile_no',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
