# Generated by Django 5.0 on 2024-11-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_address_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='image')),
                ('full_name', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=20)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
