# Generated by Django 5.0 on 2024-11-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
